model: ALFINet
simulator:
    name: WeinbergSimulator
    parameters: []
train:
    lr_scheduling: false
    nb_iter: 15
    nb_theta: 1000
    nb_x_per_theta: 500
    meta_batch_size: 16
    batch_size_x: 64
    batch_size_theta: 8
    lr: 0.0002
    save_every: 5
    test_every: 5
    loss: normal
    weight: exp
    nb_epochs: 130
test:
    nb_iter_alfi: 15
    nb_theta: 1000
    nb_x_per_theta: 500
    meta_batch_size: 16
    batch_size_x: 64
    batch_size_theta: 8
networks:
    use_grad: true
    split_theta: false
    x_data_agg:
        hidden_size: 50
        output_size: 60
    theta_data_agg:
        hidden_size: 50
        output_size: 60
    RIM:
        hidden_size: 50
        st_size: 40
        bounded: 0.2
proposal:
    name: GaussianProposal
    sigma: 0.1
plot:
    title: True
    rmse_t:
        nb_theta: 12
    hist-x:
        nb_theta: 6
        nb_samples_real: 5000
        nb_samples_gen: 5000
        nb_bins: 10
    init_box:
        nb_theta: 12
    init_rmse_t:
        nb_theta: 12
    init_comparison:
        nb_inits: 20
        nb_theta: 500
    init_MLE:
        nb_theta: 12
